CREATE TABLE ADMINISTRADOR(
	RUT_ADMIN VARCHAR2(100) NOT NULL,
	NOMBRE VARCHAR2(100),
	EMAIL VARCHAR2(100),
	CONTRASEÑA VARCHAR2(100)
);

CREATE TABLE VENDEDOR(
	RUT_VENDEDOR VARCHAR2(100) NOT NULL,
	NOMBRE VARCHAR2(100),
	EMAIL VARCHAR2(100),
	CONTRASEÑA VARCHAR2(100)
);

CREATE TABLE BOLETA(
	ID_BOLETA NUMBER NOT NULL,
	RUT_VENDEDOR VARCHAR2(100),
	ID_PRODUCTO NUMBER,
	CANTIDAD NUMBER,
	SUBTOTAL NUMBER,
	NOMBRE_PRODUCTO VARCHAR2(1000)
);

CREATE TABLE REGISTRO_VENTAS(
	N_VENTA NUMBER NOT NULL,
	RUT_VENDEDOR VARCHAR2(100),
	TOTAL NUMBER,
    FECHA DATE
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO NUMBER NOT NULL,
	NOMBRE VARCHAR2(100),
	STOCK NUMBER,
	VALOR NUMBER,
	IMAGEN VARCHAR2(990)
);


ALTER TABLE ADMINISTRADOR ADD CONSTRAINT PK_ADMIN PRIMARY KEY(RUT_ADMIN);
ALTER TABLE VENDEDOR ADD CONSTRAINT PK_VENDEDOR PRIMARY KEY(RUT_VENDEDOR);
ALTER TABLE BOLETA ADD CONSTRAINT PK_BOLETA PRIMARY KEY(ID_BOLETA);
ALTER TABLE REGISTRO_VENTAS ADD CONSTRAINT PK_rVentas PRIMARY KEY(N_VENTA);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO);

ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_VENDEDOR FOREIGN KEY(RUT_VENDEDOR) REFERENCES VENDEDOR(RUT_VENDEDOR);
ALTER TABLE REGISTRO_VENTAS ADD CONSTRAINT FK_rVENTAS FOREIGN KEY(RUT_VENDEDOR) REFERENCES VENDEDOR(RUT_VENDEDOR);


